# Generated by Django 6.0.3 on 2026-03-03 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PIB', 'Producto Interno Bruto'), ('INFLACION', 'Inflación'), ('DESEMPLEO', 'Desempleo'), ('BALANZA_COMERCIAL', 'Balanza Comercial'), ('DEUDA_PIB', 'Deuda / PIB'), ('PIB_PERCAPITA', 'PIB Per Cápita')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unidad', models.CharField(choices=[('PORCENTAJE', 'Porcentaje (%)'), ('USD', 'Dólares (USD)'), ('USD_MILES_MILLONES', 'Miles de Millones (USD)')], max_length=20)),
                ('anio', models.IntegerField()),
                ('fuente', models.CharField(choices=[('WORLD_BANK', 'World Bank API'), ('MANUAL', 'Ingreso Manual')], default='MANUAL', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='countries.pais')),
            ],
            options={
                'verbose_name': 'Indicador Económico',
                'verbose_name_plural': 'Indicadores Económicos',
                'ordering': ['-anio', 'tipo'],
                'unique_together': {('pais', 'tipo', 'anio')},
            },
        ),
    ]
