# Generated by Django 6.0.3 on 2026-03-04 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicadoreconomico',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='indicadoreconomico',
            name='anio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)]),
        ),
        migrations.AddConstraint(
            model_name='indicadoreconomico',
            constraint=models.UniqueConstraint(fields=('pais', 'tipo', 'anio'), name='unique_indicador_por_pais_anio'),
        ),
    ]
