# Generated by Django 6.0.3 on 2026-03-03 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('RIESGO', 'Riesgo de País'), ('TIPO_CAMBIO', 'Variación Tipo de Cambio'), ('INDICADOR', 'Cambio en Indicador')], default='INDICADOR', max_length=20)),
                ('severidad', models.CharField(choices=[('INFO', 'Informativa'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítica')], default='INFO', max_length=15)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='countries.pais')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
