# Generated by Django 6.0.3 on 2026-03-03 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('score_economico', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_cambiario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_estabilidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('indice_compuesto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MODERADO', 'Moderado'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MODERADO', max_length=15)),
                ('detalle_calculo', models.JSONField(blank=True, help_text='Desglose detallado de los factores de cálculo', null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices_riesgo', to='countries.pais')),
            ],
            options={
                'verbose_name': 'Índice de Riesgo',
                'verbose_name_plural': 'Índices de Riesgo',
                'ordering': ['-fecha_calculo'],
                'get_latest_by': 'fecha_calculo',
            },
        ),
    ]
