# Generated by Django 6.0.3 on 2026-03-03 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_activo', models.CharField(choices=[('RENTA_FIJA', 'Renta Fija'), ('RENTA_VARIABLE', 'Renta Variable'), ('COMMODITIES', 'Commodities'), ('MONEDA', 'Moneda')], default='RENTA_VARIABLE', max_length=20)),
                ('monto_inversion_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posiciones', to='countries.pais')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='portfolios.portafolio')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
            },
        ),
    ]
