# Generated by Django 6.0.3 on 2026-03-03 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_destino', models.CharField(default='USD', max_length=3)),
                ('tasa', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fecha', models.DateField()),
                ('variacion_porcentual', models.DecimalField(decimal_places=4, help_text='Variación respecto al cierre anterior', max_digits=7)),
                ('fuente', models.CharField(default='MANUAL', max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_de_cambio', to='countries.pais', verbose_name='País de Origen')),
            ],
            options={
                'verbose_name': 'Tipo de Cambio',
                'verbose_name_plural': 'Tipos de Cambio',
                'ordering': ['-fecha'],
                'unique_together': {('pais', 'moneda_destino', 'fecha')},
            },
        ),
    ]
