# Generated by Django 6.0.3 on 2026-03-04 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='portafolio',
            constraint=models.UniqueConstraint(fields=('usuario', 'nombre'), name='unique_portfolio_name_per_user'),
        ),
    ]
