# Generated by Django 6.0.3 on 2026-03-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo_iso', models.CharField(help_text='Código ISO de 2 letras (ej: CO, BR, MX)', max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('moneda_codigo', models.CharField(help_text='Ej: COP, BRL, MXN', max_length=3)),
                ('moneda_nombre', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('ANDINA', 'Región Andina'), ('CONO_SUR', 'Cono Sur'), ('CENTROAMERICA', 'Centroamérica'), ('CARIBE', 'Caribe')], default='ANDINA', max_length=20)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('poblacion', models.BigIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
    ]
